site_name: 'Bioinformatica em português'
site_url: 'https://lmigueel.github.io/Bioinformatica'
site_description: 'Pipelines e workflows para Bioinformatica'
site_author: 'Lucas Miguel de Carvalho'

repo_name: 'lmigueel/Bioinformatica'
repo_url: 'https://github.com/lmigueel/Bioinformatica'

nav:
  - Home: 'index.md'
  - Geral: 'geral.md'
  - Genomica: 'genomica.md'
  - Transcriptomica: 'transcriptomica.md'
  - Systems Biology: 'systems.md'
  - Linguagem R: 'linguagemR.md'
  - Outros: 'outros.md'

theme:
  name: 'material'
  palette:
    primary: 'White'
    accent: 'Light Blue'
  font:
    text: 'Nunito Sans'
    code: 'Fira Mono'
  logo:
    icon: 'book'

markdown_extensions:
  - 'admonition'
  - 'footnotes'
  - 'codehilite'
  - 'pymdownx.arithmatex'

plugins:
  - 'search'
  - 'mknotebooks'
  - i18n:
      default_language: 'pt'
      languages:
        pt:
          name: 'Português'
          locale: 'pt-BR'
          direction: 'ltr'
          translations:
            search: 'Pesquisar'
            next_page: 'Próxima página'
            previous_page: 'Página anterior'
            home: 'Início'
        en:
          name: 'English'
          locale: 'en-CA'
          direction: 'ltr'
          translations:
            search: 'Search'
            next_page: 'Next page'
            previous_page: 'Previous page'
            home: 'Home'